# drop-managed: regenerated by Drop, do not edit
"""Drop-managed global protonfixes fix.

umu-protonfixes loads ``localfixes/default.py`` for EVERY game, so this bails
immediately unless a recipe is explicitly opted into. It currently hosts the
OnlineFix co-op recipe, a port of Drop's native Rust ``prepare_onlinefix``
(src-tauri/process/src/prefix_prep.rs) — line refs below map each step back to
the Rust source of truth.

It is GATED behind ``DROP_FIX_ONLINEFIX``: Drop's Rust path owns the recipe
unless the environment sets ``DROP_FIX_ONLINEFIX=python`` (the var is inherited
by the umu child, and the Rust side defers on the same value), so the two can be
diffed against each other on a clean prefix before this becomes the default.
Everything here is best-effort — a failure never aborts a launch.
"""

import os
import shutil

try:
    from protonfixes import util
except Exception:  # only importable inside the umu-protonfixes runtime
    util = None

STEAM_ROOTS = ("~/.steam/steam", "~/.local/share/Steam", "~/.steam/root")


def main() -> None:
    """Entry point umu-protonfixes calls for every launch."""
    if os.environ.get("DROP_FIX_ONLINEFIX") == "python":
        _apply_onlinefix()


# ── OnlineFix recipe (mirrors prefix_prep.rs prepare_onlinefix :225-339) ──────


def _apply_onlinefix() -> None:
    if util is None:
        return
    try:
        install_dir = util.get_game_install_path()
    except Exception:
        return
    if not install_dir:
        return

    # Detection: OnlineFix64.dll next to the exe is the common case; UE-style
    # games nest it under Binaries/Win64, so a bounded install-tree search covers
    # both. Not present => not an OnlineFix game. (prefix_prep.rs:248-261)
    if _find_file(install_dir, "OnlineFix64.dll", 6) is None:
        return

    try:
        prefix = util.protonprefix()
    except Exception:
        return

    _stage_bridge_dlls(prefix)
    _ensure_sdk_symlinks()
    _force_active_process_pid(prefix)
    _apply_env()


def _apply_env() -> None:
    # WINEDLLOVERRIDES + STEAM_COMPAT_CLIENT_INSTALL_PATH (prefix_prep.rs:321-333).
    # Appended, not clobbered, so protonfixes'/Proton's own overrides survive
    # (util.winedll_override is the idiomatic per-dll equivalent).
    overrides = "OnlineFix64=n;SteamOverlay64=n;winmm=n,b;dnet=n;steam_api64=n"
    existing = os.environ.get("WINEDLLOVERRIDES", "")
    os.environ["WINEDLLOVERRIDES"] = (
        f"{existing};{overrides}" if existing else overrides
    )
    os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"] = os.path.expanduser(
        "~/.steam/steam"
    )


def _stage_bridge_dlls(prefix: str) -> None:
    # <pfx>/drive_c/Program Files (x86)/Steam/  (prefix_prep.rs:268-302)
    steam_dir = os.path.join(prefix, "drive_c", "Program Files (x86)", "Steam")
    try:
        os.makedirs(steam_dir, exist_ok=True)
    except OSError:
        return

    overlay = _find_live_steam_overlay_dll()
    if overlay:
        _stage(overlay, os.path.join(steam_dir, "GameOverlayRenderer64.dll"))

    lsteamclient = _find_proton_lsteamclient()
    if lsteamclient:
        _stage(lsteamclient, os.path.join(steam_dir, "steamclient64.dll"))


def _find_live_steam_overlay_dll():
    # (prefix_prep.rs:346-354)
    for root in STEAM_ROOTS:
        hit = _find_file(os.path.expanduser(root), "GameOverlayRenderer64.dll", 6)
        if hit:
            return hit
    return None


def _find_proton_lsteamclient():
    # Must be the x86_64-windows copy — the i386 one loaded as steamclient64.dll
    # fails with error 193. umu resolves PROTONPATH to an absolute dir before
    # protonfixes runs, so the direct path usually hits; the newest-wins keyword
    # search is only a fallback. (prefix_prep.rs:369-433)
    rel = os.path.join("files", "lib", "wine", "x86_64-windows", "lsteamclient.dll")
    proton = os.environ.get("PROTONPATH", "")
    if proton and os.path.isabs(proton) and os.path.isdir(proton):
        direct = os.path.join(proton, rel)
        if os.path.isfile(direct):
            return direct

    home = os.path.expanduser("~")
    roots = (
        os.path.join(home, ".local", "share", "Steam", "compatibilitytools.d"),
        os.path.join(home, ".steam", "root", "compatibilitytools.d"),
        os.path.join(home, ".local", "share", "umu"),
    )
    newest = None
    newest_mtime = -1.0
    for root in roots:
        for hit in _find_files(root, "lsteamclient.dll", 8):
            if "x86_64-windows" not in hit:
                continue
            try:
                mtime = os.path.getmtime(hit)
            except OSError:
                mtime = 0.0
            if mtime > newest_mtime:
                newest, newest_mtime = hit, mtime
    return newest


def _ensure_sdk_symlinks() -> None:
    # Proton's lsteamclient dlopen()s ~/.steam/sdk{64,32}/steamclient.so by an
    # absolute path that ignores env. Point them at the live Steam runtime.
    # (prefix_prep.rs:442-498)
    steam_root = None
    for root in STEAM_ROOTS:
        cand = os.path.expanduser(root)
        if os.path.isfile(os.path.join(cand, "linux64", "steamclient.so")):
            steam_root = cand
            break
    if steam_root is None:
        return

    home = os.path.expanduser("~")
    for sdk, linux in (("sdk64", "linux64"), ("sdk32", "linux32")):
        link = os.path.join(home, ".steam", sdk, "steamclient.so")
        target = os.path.join(steam_root, linux, "steamclient.so")
        if os.path.lexists(link):
            continue
        if not os.path.isfile(target):
            continue
        try:
            os.makedirs(os.path.dirname(link), exist_ok=True)
            os.symlink(target, link)
        except OSError:
            pass


def _force_active_process_pid(prefix: str) -> None:
    # HKCU\...\ActiveProcess\PID must be Proton's 0xfffe sentinel or OnlineFix
    # reports "steam is not launched". File-based, section-scoped, inserted if
    # missing; skipped when user.reg / the section isn't there yet.
    # (prefix_prep.rs:513-583)
    section = "[Software\\\\Valve\\\\Steam\\\\ActiveProcess]"
    pid_key = '"PID"=dword:'
    sentinel = '"PID"=dword:0000fffe'

    reg_path = os.path.join(prefix, "user.reg")
    try:
        with open(reg_path, "r", encoding="utf-8", errors="surrogateescape") as fh:
            content = fh.read()
    except OSError:
        return  # user.reg not present yet — a later launch sets it
    if section not in content:
        return

    out = []
    in_section = False
    pid_done = False
    changed = False
    for line in content.splitlines():
        if line.startswith("["):
            if in_section and not pid_done:
                out.append(sentinel)
                changed = True
            in_section = line.startswith(section)
            pid_done = False
        elif in_section and not pid_done and line.startswith(pid_key):
            pid_done = True
            if line != sentinel:
                out.append(sentinel)
                changed = True
                continue
        out.append(line)
    if in_section and not pid_done:
        out.append(sentinel)
        changed = True

    if not changed:
        return
    try:
        with open(
            reg_path, "w", encoding="utf-8", errors="surrogateescape", newline="\n"
        ) as fh:
            fh.write("\n".join(out) + "\n")
    except OSError:
        pass


# ── small helpers ────────────────────────────────────────────────────────────


def _stage(src: str, dest: str) -> None:
    # Always overwrite so a wrong-arch / stale bridge DLL self-heals.
    # (prefix_prep.rs:608-628)
    try:
        shutil.copyfile(src, dest)
    except OSError:
        pass


def _find_file(root: str, name: str, max_depth: int):
    for hit in _find_files(root, name, max_depth):
        return hit
    return None


def _find_files(root: str, name: str, max_depth: int):
    # Bounded DFS; skips unreadable dirs and doesn't follow symlinks, so a loop
    # or a huge tree can't hang the launch. (prefix_prep.rs:633-...)
    results = []
    if not os.path.isdir(root):
        return results
    root = os.path.abspath(root)
    base_depth = root.rstrip(os.sep).count(os.sep)
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        depth = dirpath.rstrip(os.sep).count(os.sep) - base_depth
        if depth >= max_depth:
            dirnames[:] = []
        if name in filenames:
            results.append(os.path.join(dirpath, name))
    return results
